/**
 * Stable, URL-safe error codes returned to API consumers.
 * Strings are part of the public contract — never repurpose an existing code.
 */
export const ErrorCode = {
  // Auth / HMAC
  HMAC_INVALID_SIGNATURE: 'HMAC_INVALID_SIGNATURE',
  HMAC_TIMESTAMP_SKEW: 'HMAC_TIMESTAMP_SKEW',
  HMAC_REPLAYED: 'HMAC_REPLAYED',
  HMAC_UNKNOWN_KEY: 'HMAC_UNKNOWN_KEY',
  HMAC_KEY_REVOKED: 'HMAC_KEY_REVOKED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Orders / trading
  ORDER_INVALID_SYMBOL: 'ORDER_INVALID_SYMBOL',
  ORDER_INVALID_QUANTITY: 'ORDER_INVALID_QUANTITY',
  ORDER_INVALID_PRICE: 'ORDER_INVALID_PRICE',
  ORDER_DUPLICATE_CLIENT_ID: 'ORDER_DUPLICATE_CLIENT_ID',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // Risk
  RISK_INSUFFICIENT_MARGIN: 'RISK_INSUFFICIENT_MARGIN',
  RISK_POSITION_LIMIT_EXCEEDED: 'RISK_POSITION_LIMIT_EXCEEDED',
  RISK_DAILY_LOSS_LIMIT: 'RISK_DAILY_LOSS_LIMIT',

  // Trades
  TRADE_NOT_FOUND: 'TRADE_NOT_FOUND',
  TRADE_HASH_CHAIN_BROKEN: 'TRADE_HASH_CHAIN_BROKEN',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;
export type ErrorCodeValue = (typeof ErrorCode)[ErrorCodeKey];
